os:
  edit: "hx -- {{filename}}"
  editAtLine: "hx -- {{filename}}:{{line}}"
  editInTerminal: true

gui:
  theme:
    selectedLineBgColor:
      - '#1e1e1e'

git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --line-numbers --paging=never
