theme = "jelly"

[editor]
line-number = "relative"
mouse = false
scrolloff = 999
true-color = true
color-modes = true
auto-format = true
clipboard-provider = "pasteboard"
popup-border = "all"
workspace-lsp-roots = ["."]
auto-reload = true

# Fork
rounded-corners = true
inline-blame = { show = "cursor-line", format = "{author} • {time-ago} • {title}", auto-fetch = false }
rainbow-brackets = true

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true
timeout = 1000

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
nbsp = "⍽"
space = " "
tab = "→"
newline = " " # ⏎
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "function-name"]
# center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[editor.file-picker]
hidden = false    # Show hidden files (vendor etc.)
git-ignore = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"D" = ["select_mode", "goto_line_end", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
C-h = ":reset-diff-change"
C-n = ["select_next_sibling"]
C-o = ":open ~/.config/helix/config.toml"

# Lazygit
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

[keys.normal.space]
s = ":w"
q = ":bc"
J = [":set-language json", ":format"]

# Forked - Helix
#
#

[editor.cmdline]
style = "popup"
use-full-height = true

[editor.cmdline.icons]
search = "/"
command = ":"
shell = "$"
general = ">"

[editor.gradient-borders]
enable = true
thickness = 1
direction = "diagonal"
start-color = "#FF4500"  # Orange Red
middle-color = "#FFD700" # Gold
end-color = "#FF69B4"    # Hot Pink
animation-speed = 1

[editor.lsp]
signature-help-position = "below"


[editor.notifications]
enable = false

[editor.notifications.shadow]
enable = false

[editor.bufferline]
render-mode = "multiple"
separator = "|"
