inherits = "bogster"

"ui.background" = {}
"ui.statusline.normal" = { bg = "bogster-teal", fg = "bogster-base1", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { bg = "bogster-orange" }
"ui.virtual.indent-guide" = { fg = "bogster-base2" }
"ui.virtual.whitespace" = { fg = "bogster-base1" }
"punctuation.delimiter" = "bogster-base4"

"diagnostic.unnecessary" = { modifiers = ["crossed_out", "dim"] }
"ui.cursor.match" = { bg = "bogster-base3" }

"type" = { fg = "bogster-blue", modifiers = ["underlined", "slow_blink"] }
"type.builtin" = { fg = "bogster-blue", modifiers = ["bold"] }
"string" = "bogster-fg0"
"comment" = "bogster-base4"
"variable" = "bogster-lblue"
"function" = { fg = "bogster-purp", modifiers = ["italic"] }

"ui.popup" = {}
"ui.bufferline" = { fg = 'bogster-base2' }
"ui.bufferline.active" = { fg = 'bogster-base3', bg = 'bogster-yellow' }
"ui.window" = { bg = "bogster-base0" }


[palette]
bogster-teal = "#00988e"
